version: '3.4'
name: "dynamic_links"

services:
  dynamiclinks:
    image: ${DOCKER_REGISTRY-}dynamiclinks
    build:
      context: .
      dockerfile: DynamicLinks/Dockerfile
    container_name: root_node

  redis:
      image: redislabs/redismod:latest
      container_name: redis
      ports: 
        - 6379:6379
  
  redis-client:
    image: oblakstudio/redisinsight:latest
    container_name: redis-client
    ports: 
    - 5540:5540
